using UnityEngine;
using System.Collections;

public enum GP_AppStateStatusCodes  {

	STATUS_OK = 0,
	STATUS_INTERNAL_ERROR = 1,
	STATUS_CLIENT_RECONNECT_REQUIRED = 2,
	STATUS_NETWORK_ERROR_STALE_DATA = 3,
	STATUS_NETWORK_ERROR_NO_DATA = 4,
	STATUS_NETWORK_ERROR_OPERATION_DEFERRED = 5,
	STATUS_NETWORK_ERROR_OPERATION_FAILED = 6,
	STATUS_DEVELOPER_ERROR = 7,


	STATUS_INTERRUPTED = 14,
	STATUS_TIMEOUT = 15,

	STATUS_WRITE_OUT_OF_DATE_VERSION = 2000,
	STATUS_WRITE_SIZE_EXCEEDED = 2001,
	STATUS_STATE_KEY_NOT_FOUND = 2002,
	STATUS_STATE_KEY_LIMIT_EXCEEDED = 2003

	
}
