using UnityEngine;
using System.Collections;

public enum GP_GamesActivityResultCodes {



	RESULT_OK = -1,
	RESULT_CANCELED = 0,
	RESULT_FIRST_USER = 1,



	RESULT_RECONNECT_REQUIRED = 10001,
	RESULT_SIGN_IN_FAILED = 10002,
	RESULT_LICENSE_FAILED = 10003,
	RESULT_APP_MISCONFIGURED = 10004,
	RESULT_LEFT_ROOM = 10005,
	RESULT_NETWORK_FAILURE = 10006,
	RESULT_SEND_REQUEST_FAILED = 10007,
	RESULT_INVALID_ROOM = 10008
}
