////////////////////////////////////////////////////////////////////////////////
//  
// @module Common Android Native Lib
// @author Osipov Stanislav (Stan's Assets) 
// @support stans.assets@gmail.com 
//
////////////////////////////////////////////////////////////////////////////////


 

using System;


public enum GP_GamesStatusCodes {

	//results description can be found at:
	//http://developer.android.com/reference/com/google/android/gms/games/GamesStatusCodes.html

	STATUS_OK = 0,
	STATUS_INTERNAL_ERROR = 1,
	STATUS_CLIENT_RECONNECT_REQUIRED = 2,
	STATUS_NETWORK_ERROR_STALE_DATA = 3,
	STATUS_NETWORK_ERROR_NO_DATA = 4,
	STATUS_NETWORK_ERROR_OPERATION_DEFERRED = 5,
	STATUS_NETWORK_ERROR_OPERATION_FAILED = 6,
	STATUS_LICENSE_CHECK_FAILED = 7,
	STATUS_APP_MISCONFIGURED = 8,
	STATUS_GAME_NOT_FOUND = 9,
	STATUS_INTERRUPTED = 14,
	STATUS_TIMEOUT = 15,


	STATUS_REQUEST_UPDATE_PARTIAL_SUCCESS = 2000,
	STATUS_REQUEST_UPDATE_TOTAL_FAILURE = 2001,

	STATUS_ACHIEVEMENT_UNLOCK_FAILURE = 3000,
	STATUS_ACHIEVEMENT_UNKNOWN = 3001,
	STATUS_ACHIEVEMENT_UNLOCKED = 3003,
	STATUS_ACHIEVEMENT_NOT_INCREMENTAL = 3002,

	STATUS_MULTIPLAYER_ERROR_CREATION_NOT_ALLOWED = 6000,
	STATUS_MULTIPLAYER_ERROR_NOT_TRUSTED_TESTER = 6001,
	STATUS_MULTIPLAYER_ERROR_INVALID_MULTIPLAYER_TYPE = 6002,
	STATUS_MULTIPLAYER_DISABLED = 6003,
	STATUS_MULTIPLAYER_ERROR_INVALID_OPERATION = 6004,



	STATUS_MATCH_ERROR_INVALID_PARTICIPANT_STATE = 6500,
	STATUS_MATCH_ERROR_INACTIVE_MATCH = 6501,
	STATUS_MATCH_ERROR_INVALID_MATCH_STATE = 6502,
	STATUS_MATCH_ERROR_OUT_OF_DATE_VERSION = 6503,
	STATUS_MATCH_ERROR_INVALID_MATCH_RESULTS = 6504,
	STATUS_MATCH_ERROR_ALREADY_REMATCHED = 6505,
	STATUS_MATCH_NOT_FOUND = 6506,
	STATUS_MATCH_ERROR_LOCALLY_MODIFIED = 6507,



	STATUS_REAL_TIME_CONNECTION_FAILED = 7000,
	STATUS_REAL_TIME_MESSAGE_SEND_FAILED = 7001,
	STATUS_INVALID_REAL_TIME_ROOM_ID = 7002,
	STATUS_PARTICIPANT_NOT_CONNECTED = 7003,
	STATUS_REAL_TIME_ROOM_NOT_JOINED = 7004,
	STATUS_REAL_TIME_INACTIVE_ROOM = 7005,

	STATUS_OPERATION_IN_FLIGHT = 7007,
	

	STATUS_UNKNOWN = 99999

}


