//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum LearningBlockDataFocus
  {
      None = 0,
      Letters = 1,
      Symbols = 2,
      Sounds = 3,
      Words = 4,
      Phrases = 5,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
