//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum LetterDataKind
  {
      Letter = 1,
      Symbol = 2,
      DiacriticCombo = 3,
      LetterVariation = 4,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
