//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum LetterDataSunMoon
  {
      None = 0,
      Moon = 1,
      Sun = 2,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
