//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum MiniGameDataType
  {
      MiniGame = 1,
      Assessment = 2,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
