//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Database
{
  public enum PhraseDataCategory
  {
      None = 0,
      Question = 1,
      Reply = 2,
      Greetings = 3,
      Year = 4,
      Sentence = 5,
      phrase = 6,
      expression = 7,
      sentence = 8,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
