//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum PhraseDataCategory
  {
      None = 0,
      Question = 1,
      Reply = 2,
      Greetings = 3,
      Year = 4,
      Sentence = 5,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
