//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum PlaySessionDataOrder
  {
      Sequence = 1,
      Random = 2,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
