//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Rewards
{
    public enum RewardTypes
    {
        reward = 0,
        texture = 1,
        decal = 2,
    }
}

// this is not currently used!
namespace EA4S.Database
{
    public enum RewardDataCategory
    {
        DogProp = 1,
        DogSkin = 2,
        DogAnimation = 3,
    }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
