//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum RewardDataCategory
  {
      DogProp = 1,
      DogSkin = 2,
      DogAnimation = 3,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
