//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataKind
  {
      Adjective = 1,
      Verb = 2,
      Article = 3,
      Preposition = 4,
      Noun = 5,
      UI = 6,
      Adverb = 7,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
