namespace EA4S.Database
{
    public enum WordDataCategory
    {
        None = 0,
        People = 1,
        Conjunctions = 2,
        Feeling = 3,
        Food = 4,
        FamilyMember = 5,
        BodyPart = 6,
        Thing = 7,
        Place = 8,
        Sport = 9,
        Animal = 10,
        General = 11,
        Furniture = 12,
        Size = 13,
        Nature = 14,
        Vehicle = 15,
        Job = 16,
        Clothes = 17,
        Color = 18,
        Expression = 19,
        Time = 20,
        Greetings = 21,
        Direction = 22,
        Question = 23,
        Position = 24,
        Imperative = 25,
        Number = 26,
        NumberOrdinal = 27,
        Name = 28,
        Weather = 29,
        Shape = 30,
    }
}
