//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataKind
  {
      Adjective = 1,
      Verb = 2,
      Article = 3,
      Noun = 4,
      Adverb = 5,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
