//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Database
{
  public enum WordDataCategory
  {
      None = 0,
      FamilyMember = 1,
      People = 2,
      Feeling = 3,
      Food = 4,
      BodyPart = 5,
      Thing = 6,
      Place = 7,
      Sport = 8,
      Animal = 9,
      General = 10,
      Furniture = 11,
      Size = 12,
      Nature = 13,
      Vehicle = 14,
      Job = 15,
      Clothes = 16,
      Color = 17,
      Time = 18,
      Number = 19,
      NumberOrdinal = 20,
      Shape = 21,
      Conjunctions = 22,
      Expression = 23,
      Greetings = 24,
      Direction = 25,
      Question = 26,
      Position = 27,
      Imperative = 28,
      Name = 29,
      Weather = 30,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
