//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataCategory
  {
      None = 0,
      People = 1,
      Food = 2,
      FamilyMember = 3,
      BodyPart = 4,
      Place = 5,
      Sport = 6,
      Animal = 7,
      General = 8,
      Furniture = 9,
      Size = 10,
      Thing = 11,
      Nature = 12,
      Vehicle = 13,
      Job = 14,
      Color = 15,
      Clothes = 16,
      Time = 17,
      Number = 18,
      nature = 19,
      feelings = 20,
      Shape = 21,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
