//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Database
{
  public enum WordDataKind
  {
      Noun = 1,
      Adjective = 2,
      Verb = 3,
      Article = 4,
      UI = 5,
      Adverb = 6,
      Preposition = 7,
      Pronoun = 8,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
