using System.Collections.Generic;
using Antura.Core;
using Antura.Database;
using Antura.Helpers;
using UnityEngine;

namespace Antura.Teacher
{
    /// <summary>
    /// Selects alterations of letters at random
    /// * Question: The alteration to find
    /// * Correct answers: The correct alteration
    /// * Wrong answers: Wrong alteration
    /// </summary>
    public class RandomLetterAlterationsQuestionBuilder : IQuestionBuilder
    {
        // focus: Letters, either different or alterations of the same letter
        // pack history filter: parameterized
        // journey: enabled

        private int nPacks;
        private int nCorrect;
        private int nWrong;
        private bool firstCorrectIsQuestion;
        private QuestionBuilderParameters parameters;
        private LetterAlterationFilters letterAlterationFilters;
        private LetterEqualityStrictness letterEqualityStrictness;  // Strictness to assign to letters for equality, when generated by this builder

        public QuestionBuilderParameters Parameters
        {
            get { return this.parameters; }
        }
       
        public RandomLetterAlterationsQuestionBuilder(int nPacks, int nCorrect = 1, int nWrong = 0, 
            bool firstCorrectIsQuestion = false,
            LetterEqualityStrictness letterEqualityStrictness = LetterEqualityStrictness.WithActualForm,
            LetterAlterationFilters letterAlterationFilters = null,
            QuestionBuilderParameters parameters = null
            )
        {
            if (letterAlterationFilters == null) letterAlterationFilters = new LetterAlterationFilters();

            if (parameters == null)
            {
                parameters = new QuestionBuilderParameters();
            }

            this.nPacks = nPacks;
            this.nCorrect = nCorrect;
            this.nWrong = nWrong;
            this.firstCorrectIsQuestion = firstCorrectIsQuestion;
            this.parameters = parameters;
            this.letterAlterationFilters = letterAlterationFilters;
            this.letterEqualityStrictness = letterEqualityStrictness;

            // Forced filters
            // We need only base letters as the basis here
            this.parameters.letterFilters.excludeDiacritics = LetterFilters.ExcludeDiacritics.All;
            this.parameters.letterFilters.excludeLetterVariations = LetterFilters.ExcludeLetterVariations.All;
            this.parameters.letterFilters.excludeDiphthongs = true;
        }

        private List<string> previousPacksIDs = new List<string>();

        public List<QuestionPackData> CreateAllQuestionPacks()
        {
            previousPacksIDs.Clear();

            var packs = new List<QuestionPackData>();
            for (int pack_i = 0; pack_i < nPacks; pack_i++)
            {
                var pack = CreateSingleQuestionPackData();
                packs.Add(pack);
            }
            return packs;
        }

        private QuestionPackData CreateSingleQuestionPackData()
        {
            var teacher = AppManager.I.Teacher;
            var vocabularyHelper = AppManager.I.VocabularyHelper;

            // First, get all letters (only base letters, tho, due to forced letter filters)
            int nBaseLettersRequired = 1;
            if (letterAlterationFilters.differentBaseLetters) nBaseLettersRequired = nCorrect + nWrong;
            var chosenLetters = teacher.VocabularyAi.SelectData(
                () => vocabularyHelper.GetAllLetters(parameters.letterFilters),
                    new SelectionParameters(parameters.correctSeverity, nRequired: nBaseLettersRequired, useJourney: parameters.useJourneyForCorrect,
                        packListHistory: parameters.correctChoicesHistory, filteringIds: previousPacksIDs)
            );
            var baseLetters = chosenLetters;

            // Then, find all the different variations and add them to a pool
            var letterPool = new List<LetterData>();

            // Filter: only 1 base or multiples
            if (!letterAlterationFilters.differentBaseLetters)
            {
                var chosenLetter = baseLetters.RandomSelectOne();
                baseLetters.Clear();
                baseLetters.Add(chosenLetter);
            }

            //Debug.Log("N base letters: " + baseLetters.Count);
            // Get all alterations for the given bases
            foreach (var baseLetter in baseLetters)
            {
                // Check all alterations of this base letter
                var letterVariations = vocabularyHelper.GetLettersWithBase(baseLetter.GetId());
                List<LetterData> availableVariations = new List<LetterData>();
                foreach (var letterData in letterVariations)
                {
                    if (!vocabularyHelper.FilterByDiacritics(letterAlterationFilters.ExcludeDiacritics, letterData)) continue;
                    if (!vocabularyHelper.FilterByLetterVariations(letterAlterationFilters.ExcludeLetterVariations, letterData)) continue;
                    if (!vocabularyHelper.FilterByDipthongs(letterAlterationFilters.excludeDipthongs, letterData)) continue;
                    availableVariations.Add(letterData);
                }
                //Debug.Log("N availableVariations  " + availableVariations.Count + "  for " + baseLetter.GetId());

                if (letterAlterationFilters.includeForms)
                {
                    // Add forms too to the variations, if needed
                    List<LetterData> basesForForms = new List<LetterData>(availableVariations);
                    basesForForms.Add(baseLetter);
                    foreach (var baseForForm in basesForForms)
                    {
                        var availableForms = vocabularyHelper.GetLettersWithForcedForms(baseForForm);
                        letterPool.AddRange(availableForms);
                    }
                }
                else
                {
                    // Add just the isolated versions
                    letterPool.Add(baseLetter);
                    letterPool.AddRange(availableVariations);
                }
            }

            var correctAnswers = letterPool.RandomSelect(nCorrect);
            var wrongAnswers = letterPool;
            foreach (LetterData data in correctAnswers)
                wrongAnswers.Remove(data);
            wrongAnswers = wrongAnswers.RandomSelect(Mathf.Min(nWrong,wrongAnswers.Count));

            var question = baseLetters[0];
            if (firstCorrectIsQuestion) question = correctAnswers[0];

            if (ConfigAI.VerboseQuestionPacks)
            {
                string debugString = "--------- TEACHER: question pack result ---------";
                debugString += "\nQuestion: " + question;
                debugString += "\nCorrect Answers: " + correctAnswers.Count;
                foreach (var l in correctAnswers) debugString += " " + l;
                debugString += "\nWrong Answers: " + wrongAnswers.Count;
                foreach (var l in wrongAnswers) debugString += " " + l;
                ConfigAI.AppendToTeacherReport(debugString);
            }

            // Set strictness for the comparisons
            question = vocabularyHelper.ForceEqualityStrictness(question, letterEqualityStrictness);
            correctAnswers = vocabularyHelper.ForceEqualityStrictness(correctAnswers, letterEqualityStrictness);
            wrongAnswers = vocabularyHelper.ForceEqualityStrictness(wrongAnswers, letterEqualityStrictness);

            return QuestionPackData.Create(question, correctAnswers, wrongAnswers);
        }

    }
}