//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum LetterDataKind
  {
      Letter = 1,
      Combination = 2,
      Symbol = 3,
      Special = 4,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
