//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum LetterDataType
  {
      None = 0,
      LongVowel = 1,
      Consonant = 2,
      Powerful = 3,
      DiacriticSymbol = 4,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
