//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum PlaySessionDataOrder
  {
      Sequence = 0,
      Random = 1,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
