//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataForm
  {
      Singular = 0,
      Plural = 1,
      Dual = 2,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
