//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataCategory
  {
      None = 0,
      Color = 1,
      Fruit = 2,
      FamilyMember = 3,
      BodyPart = 4,
      Place = 5,
      Sport = 6,
      Animal = 7,
      Thing = 8,
      Food = 9,
      Vehicle = 10,
      Job = 11,
      Vegetable = 12,
      Time = 13,
      Nature = 14,
      Number = 15,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
