//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataKind
  {
      Adjective = 1,
      Article = 2,
      Noun = 3,
      Verb = 4,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
