//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace EA4S.Db
{
  public enum WordDataArticle
  {
      None = 0,
      Determinative = 1,
      Indeterminative = 2,
  }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
