using UnityEngine;
using System.Collections;

public enum AN_LicenseErrorCode {
	ERROR_NONE,
	ERROR_RETRY,
	ERROR_CHECK_IN_PROGRESS,
	ERROR_INVALID_PACKAGE_NAME,
	ERROR_INVALID_PUBLIC_KEY,
	ERROR_MISSING_PERMISSION,
	ERROR_NON_MATCHING_UID,
	ERROR_NOT_MARKET_MANAGED,
	ERROR_UNKNOWN
}
